# Generated by Django 5.2.2 on 2025-06-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_agerange_brand_category_color_finishtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hex_value',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, to='home.color'),
        ),
    ]
