# Generated by Django 5.2.2 on 2025-06-19 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_searchlog_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='timestamp',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='searchlog',
            old_name='timestamp',
            new_name='date_added',
        ),
    ]
