# Generated by Django 5.2.2 on 2025-06-29 01:55

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_product_image_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='browsinghistory',
            name='viewed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
