# Generated by Django 5.2.2 on 2025-06-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_shippingaddress_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='apartmentadress',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
