# Generated by Django 5.2.2 on 2025-06-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_shippingaddress_apartmentadress_shippingaddress_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('amz', 'AmzLayter'), ('viettin', 'Viettinbank')], default='cash', max_length=20),
        ),
    ]
