# Generated by Django 5.2.2 on 2025-06-29 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_shippingaddress_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='apartmentadress',
            new_name='apartmentaddress',
        ),
    ]
