# Generated by Django 5.2.2 on 2025-06-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_apartmentadress_shippingaddress_apartmentaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_status',
            field=models.CharField(choices=[('processing', 'Đang xử lý'), ('shipping', 'Đang giao'), ('delivered', 'Đã giao'), ('cancelled', 'Đã hủy')], default='processing', max_length=20),
        ),
    ]
