# Generated by Django 5.2.2 on 2025-07-01 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_shippingaddress_shipping_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_status',
            field=models.CharField(choices=[('processing', 'Đang xử lý'), ('shipping', 'Đang giao'), ('delivered', 'Đã giao'), ('cancelled', 'Đã hủy')], default='shipping', max_length=20),
        ),
    ]
