# Generated by Django 5.2.2 on 2025-07-03 07:17

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_shippingaddress_shipping_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='review_images/', validators=[home.models.validate_image_extension]),
        ),
    ]
