# Generated by Django 5.2.2 on 2025-07-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_review_image_alter_shippingaddress_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discounted_price_at_purchase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_at_purchase',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
